/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: accounts.proto */

#ifndef PROTOBUF_C_accounts_2eproto__INCLUDED
#define PROTOBUF_C_accounts_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Accounts__Order Accounts__Order;
typedef struct _Accounts__Balance Accounts__Balance;
typedef struct _Accounts__Account Accounts__Account;


/* --- enums --- */

typedef enum _Accounts__OrderSide {
  ACCOUNTS__ORDER_SIDE__BUY = 0,
  ACCOUNTS__ORDER_SIDE__SELL = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(ACCOUNTS__ORDER_SIDE)
} Accounts__OrderSide;
typedef enum _Accounts__OrderType {
  ACCOUNTS__ORDER_TYPE__MARKET = 0,
  ACCOUNTS__ORDER_TYPE__LIMIT = 1,
  ACCOUNTS__ORDER_TYPE__STOP = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(ACCOUNTS__ORDER_TYPE)
} Accounts__OrderType;

/* --- messages --- */

struct  _Accounts__Order
{
  ProtobufCMessage base;
  int32_t id;
  char *symbol;
  Accounts__OrderSide side;
  Accounts__OrderType type;
  double price;
  double volume;
};
#define ACCOUNTS__ORDER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&accounts__order__descriptor) \
    , 0, (char *)protobuf_c_empty_string, ACCOUNTS__ORDER_SIDE__BUY, ACCOUNTS__ORDER_TYPE__MARKET, 0, 0 }


struct  _Accounts__Balance
{
  ProtobufCMessage base;
  char *currency;
  double amount;
};
#define ACCOUNTS__BALANCE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&accounts__balance__descriptor) \
    , (char *)protobuf_c_empty_string, 0 }


struct  _Accounts__Account
{
  ProtobufCMessage base;
  int32_t id;
  char *name;
  Accounts__Balance *wallet;
  size_t n_orders;
  Accounts__Order **orders;
};
#define ACCOUNTS__ACCOUNT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&accounts__account__descriptor) \
    , 0, (char *)protobuf_c_empty_string, NULL, 0,NULL }


/* Accounts__Order methods */
void   accounts__order__init
                     (Accounts__Order         *message);
size_t accounts__order__get_packed_size
                     (const Accounts__Order   *message);
size_t accounts__order__pack
                     (const Accounts__Order   *message,
                      uint8_t             *out);
size_t accounts__order__pack_to_buffer
                     (const Accounts__Order   *message,
                      ProtobufCBuffer     *buffer);
Accounts__Order *
       accounts__order__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   accounts__order__free_unpacked
                     (Accounts__Order *message,
                      ProtobufCAllocator *allocator);
/* Accounts__Balance methods */
void   accounts__balance__init
                     (Accounts__Balance         *message);
size_t accounts__balance__get_packed_size
                     (const Accounts__Balance   *message);
size_t accounts__balance__pack
                     (const Accounts__Balance   *message,
                      uint8_t             *out);
size_t accounts__balance__pack_to_buffer
                     (const Accounts__Balance   *message,
                      ProtobufCBuffer     *buffer);
Accounts__Balance *
       accounts__balance__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   accounts__balance__free_unpacked
                     (Accounts__Balance *message,
                      ProtobufCAllocator *allocator);
/* Accounts__Account methods */
void   accounts__account__init
                     (Accounts__Account         *message);
size_t accounts__account__get_packed_size
                     (const Accounts__Account   *message);
size_t accounts__account__pack
                     (const Accounts__Account   *message,
                      uint8_t             *out);
size_t accounts__account__pack_to_buffer
                     (const Accounts__Account   *message,
                      ProtobufCBuffer     *buffer);
Accounts__Account *
       accounts__account__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   accounts__account__free_unpacked
                     (Accounts__Account *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Accounts__Order_Closure)
                 (const Accounts__Order *message,
                  void *closure_data);
typedef void (*Accounts__Balance_Closure)
                 (const Accounts__Balance *message,
                  void *closure_data);
typedef void (*Accounts__Account_Closure)
                 (const Accounts__Account *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    accounts__order_side__descriptor;
extern const ProtobufCEnumDescriptor    accounts__order_type__descriptor;
extern const ProtobufCMessageDescriptor accounts__order__descriptor;
extern const ProtobufCMessageDescriptor accounts__balance__descriptor;
extern const ProtobufCMessageDescriptor accounts__account__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_accounts_2eproto__INCLUDED */
