/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: accounts.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "accounts.pb-c.h"
void   accounts__order__init
                     (Accounts__Order         *message)
{
  static const Accounts__Order init_value = ACCOUNTS__ORDER__INIT;
  *message = init_value;
}
size_t accounts__order__get_packed_size
                     (const Accounts__Order *message)
{
  assert(message->base.descriptor == &accounts__order__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t accounts__order__pack
                     (const Accounts__Order *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &accounts__order__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t accounts__order__pack_to_buffer
                     (const Accounts__Order *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &accounts__order__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Accounts__Order *
       accounts__order__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Accounts__Order *)
     protobuf_c_message_unpack (&accounts__order__descriptor,
                                allocator, len, data);
}
void   accounts__order__free_unpacked
                     (Accounts__Order *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &accounts__order__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   accounts__balance__init
                     (Accounts__Balance         *message)
{
  static const Accounts__Balance init_value = ACCOUNTS__BALANCE__INIT;
  *message = init_value;
}
size_t accounts__balance__get_packed_size
                     (const Accounts__Balance *message)
{
  assert(message->base.descriptor == &accounts__balance__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t accounts__balance__pack
                     (const Accounts__Balance *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &accounts__balance__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t accounts__balance__pack_to_buffer
                     (const Accounts__Balance *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &accounts__balance__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Accounts__Balance *
       accounts__balance__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Accounts__Balance *)
     protobuf_c_message_unpack (&accounts__balance__descriptor,
                                allocator, len, data);
}
void   accounts__balance__free_unpacked
                     (Accounts__Balance *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &accounts__balance__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   accounts__account__init
                     (Accounts__Account         *message)
{
  static const Accounts__Account init_value = ACCOUNTS__ACCOUNT__INIT;
  *message = init_value;
}
size_t accounts__account__get_packed_size
                     (const Accounts__Account *message)
{
  assert(message->base.descriptor == &accounts__account__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t accounts__account__pack
                     (const Accounts__Account *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &accounts__account__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t accounts__account__pack_to_buffer
                     (const Accounts__Account *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &accounts__account__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Accounts__Account *
       accounts__account__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Accounts__Account *)
     protobuf_c_message_unpack (&accounts__account__descriptor,
                                allocator, len, data);
}
void   accounts__account__free_unpacked
                     (Accounts__Account *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &accounts__account__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor accounts__order__field_descriptors[6] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Accounts__Order, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "symbol",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Accounts__Order, symbol),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "side",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Accounts__Order, side),
    &accounts__order_side__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Accounts__Order, type),
    &accounts__order_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "price",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Accounts__Order, price),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "volume",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Accounts__Order, volume),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned accounts__order__field_indices_by_name[] = {
  0,   /* field[0] = id */
  4,   /* field[4] = price */
  2,   /* field[2] = side */
  1,   /* field[1] = symbol */
  3,   /* field[3] = type */
  5,   /* field[5] = volume */
};
static const ProtobufCIntRange accounts__order__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor accounts__order__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "accounts.Order",
  "Order",
  "Accounts__Order",
  "accounts",
  sizeof(Accounts__Order),
  6,
  accounts__order__field_descriptors,
  accounts__order__field_indices_by_name,
  1,  accounts__order__number_ranges,
  (ProtobufCMessageInit) accounts__order__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor accounts__balance__field_descriptors[2] =
{
  {
    "currency",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Accounts__Balance, currency),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "amount",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Accounts__Balance, amount),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned accounts__balance__field_indices_by_name[] = {
  1,   /* field[1] = amount */
  0,   /* field[0] = currency */
};
static const ProtobufCIntRange accounts__balance__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor accounts__balance__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "accounts.Balance",
  "Balance",
  "Accounts__Balance",
  "accounts",
  sizeof(Accounts__Balance),
  2,
  accounts__balance__field_descriptors,
  accounts__balance__field_indices_by_name,
  1,  accounts__balance__number_ranges,
  (ProtobufCMessageInit) accounts__balance__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor accounts__account__field_descriptors[4] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Accounts__Account, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Accounts__Account, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wallet",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Accounts__Account, wallet),
    &accounts__balance__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "orders",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Accounts__Account, n_orders),
    offsetof(Accounts__Account, orders),
    &accounts__order__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned accounts__account__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = name */
  3,   /* field[3] = orders */
  2,   /* field[2] = wallet */
};
static const ProtobufCIntRange accounts__account__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor accounts__account__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "accounts.Account",
  "Account",
  "Accounts__Account",
  "accounts",
  sizeof(Accounts__Account),
  4,
  accounts__account__field_descriptors,
  accounts__account__field_indices_by_name,
  1,  accounts__account__number_ranges,
  (ProtobufCMessageInit) accounts__account__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue accounts__order_side__enum_values_by_number[2] =
{
  { "BUY", "ACCOUNTS__ORDER_SIDE__BUY", 0 },
  { "SELL", "ACCOUNTS__ORDER_SIDE__SELL", 1 },
};
static const ProtobufCIntRange accounts__order_side__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex accounts__order_side__enum_values_by_name[2] =
{
  { "BUY", 0 },
  { "SELL", 1 },
};
const ProtobufCEnumDescriptor accounts__order_side__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "accounts.OrderSide",
  "OrderSide",
  "Accounts__OrderSide",
  "accounts",
  2,
  accounts__order_side__enum_values_by_number,
  2,
  accounts__order_side__enum_values_by_name,
  1,
  accounts__order_side__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue accounts__order_type__enum_values_by_number[3] =
{
  { "MARKET", "ACCOUNTS__ORDER_TYPE__MARKET", 0 },
  { "LIMIT", "ACCOUNTS__ORDER_TYPE__LIMIT", 1 },
  { "STOP", "ACCOUNTS__ORDER_TYPE__STOP", 2 },
};
static const ProtobufCIntRange accounts__order_type__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex accounts__order_type__enum_values_by_name[3] =
{
  { "LIMIT", 1 },
  { "MARKET", 0 },
  { "STOP", 2 },
};
const ProtobufCEnumDescriptor accounts__order_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "accounts.OrderType",
  "OrderType",
  "Accounts__OrderType",
  "accounts",
  3,
  accounts__order_type__enum_values_by_number,
  3,
  accounts__order_type__enum_values_by_name,
  1,
  accounts__order_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
